### ISSUE TITLE
access winccoa with its C# API through python script

### ISSUE THREAD

**Issue by davesliu** [vogler75/oa4j-wss#1]
Hello,

I want to use python script to interact with WinCC OA.
As WinCC OA has provide a C# API library, I can use the pythonnet to call the C# API.
But when I use the python script to call the Init() function of C# API, it always crashed.

Could you help to give some suggestions on how to interact with WinCC OA through python?

Thanks

**Comment by dkal-synertec** [comment]
@davesliu did you ever find a solution for how to interact with WinCC OA through python

**Comment by davesliu** [comment]
@dkal-synertec  not possible.
